# Generated by Django 4.0.5 on 2022-06-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('authors', models.ManyToManyField(related_name='technology', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.status', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала миссии')),
                ('end_date', models.DateField(verbose_name='Дата окончания миссии')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.planet', verbose_name='Планета')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.status', verbose_name='Статус')),
            ],
        ),
    ]
