# Generated by Django 4.0.5 on 2022-06-10 16:48

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('mass', models.CharField(max_length=50, verbose_name='Масса')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Небесное тело',
                'verbose_name_plural': 'Небесные тела',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение')),
                ('authors', models.ManyToManyField(related_name='technology', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала миссии')),
                ('end_date', models.DateField(verbose_name='Дата окончания миссии')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение')),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.spaceobject', verbose_name='Планета')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.mission', verbose_name='Миссия')),
                ('space_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.spaceobject', verbose_name='Небесное тело')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.technology', verbose_name='Технология')),
            ],
        ),
    ]
