# Generated by Django 4.0.5 on 2022-06-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Миссия', 'verbose_name_plural': 'Миссии'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
        migrations.AddField(
            model_name='planet',
            name='area',
            field=models.IntegerField(default=1, verbose_name='Площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='mass',
            field=models.CharField(default=1, max_length=50, verbose_name='Масса'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Satellites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.planet', verbose_name='Планета')),
            ],
        ),
    ]
