# Generated by Django 4.0.5 on 2022-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_spaceobject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceobject',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Площадь'),
        ),
    ]
